# max time
max_time: 100.0
# simulation update frequendy
sim_freq: 10.0
# weight of motion noise
sigmaM: 1.5
# sigma for floating effect
sigmaF: 0.0
# sigma for sensor model
sigmaS_R: 0.1
sigmaS_T: 0.05
# sigma for global localizaiton
sigmaGlobalLocR: 3.0
sigmaGlobalLocT: 0.5
# thresholds and rates to generate accelerations (repulsive and attractive)
repul_thresh: 10.0
repul_rate: 0.05
attr_thresh: 1.0
attr_rate: 0.01
fric_rate: 0.6 # friction
# control rate
ctrl_rate: 1.0
# control max
ctrl_max: 1.0
# weights for motion model
alpha1M: 10.0
alpha2M: 1.0
betaM: 0.5
# mode
mode: 1
# mode2 rate
mode2_rate1: 2.0
mode2_rate2: 2.0
# mode3 rate
mode3_rate: 2.0
mode3_bias: 1.5
# enable_update_step
enable_update_step: true
# enable bidirectional mutual update
enable_bidirectional: true
# global localization
enable_global_loc: true
# global localization at every specified steps
global_loc_steps: 1
# network topology
# star, loop, complete, dynamic
topology: dynamic
# radius of communication area (used when topology is set to dynamic)
comm_radius: 10.0
# robot's locations
robots:
  -
    - 0.0
    - 0.0
  -
    - 1.0
    - 0.0
  -
    - 2.0
    - 0.0
  -
    - 2.0
    - 1.0
  -
    - 2.0
    - 2.0
  -
    - 1.0
    - 2.0
  -
    - 0.0
    - 2.0
  -
    - 0.0
    - 1.0
# random order to update estimates?
enable_random_order: true
# probabilistically update?
enable_prob_update: true
prob_update_p: 1
# every N time steps to plot
plot_interval: 10
