# max time
max_time: 100.0
# simulation update frequendy
sim_freq: 10.0
# weight of motion noise
sigmaM: 1.5
# sigma for floating effect
sigmaF: 0.0
# sigma for sensor model
sigmaS_R: 0.1
sigmaS_T: 0.05
# sigma for global localizaiton
sigmaGlobalLocR: 3.0
sigmaGlobalLocT: 0.5
# thresholds and rates to generate accelerations (repulsive and attractive)
repul_thresh: 10.0
repul_rate: 0.1
attr_thresh: 3.0
attr_rate: 0.1
fric_rate: 0.6 # friction
# control rate
ctrl_rate: 1.0
# control max
ctrl_max: 1.0
# weights for motion model
alphaM: 0.5
betaM: 0.01
# mode
mode: 2
# radius of communication area
comm_radius: 10.0
# enable_update_step
enable_update_step: true
# enable bidirectional mutual update
enable_bidirectional: true
# global localization
enable_global_loc: true
# global localization at every specified steps
global_loc_steps: 1
# network topology
topology: star
# robot's locations
robots:
  -
    - 1.0
    - 2.0
  -
    - 3.0
    - 4.0
  -
    - 5.0
    - 6.0
# random order to update estimates?
enable_random_order: true
# probabilistically update?
enable_prob_update: true
prob_update_p: 0.5
# every N time steps to plot
plot_interval: 100
