field_size: 50.0
max_time_steps: 1000
deltaT: 0.1
sigmaM: 1.5
sigmaF: 0.0
sigmaS:         0.1
sigmaGlobalLoc: 3
n_robots: 5
robots:
  - x: 0.5
  - x: 2.0
  - x: 3.5
  - x: 5.0
  - x: 6.5
ctrl_rate: 1
ctrl_max: 1
enable_update_step: false
global_loc: false
global_loc_steps: 1
mode: 1
random_order: true
prob_update: true
prob_update_p: 0.5
enable_loop: false
