# max time
max_time: 100.0
# simulation update frequendy
sim_freq: 10.0
# use random seed
use_random_seed: true
# random seed to give
random_seed: 5000
# weight of motion noise
sigmaM: 1.5
# sigma for floating effect
sigmaF: 0.0
# sigma for sensor model
sigmaS_R: 0.1
sigmaS_T: 0.05
# sigma for global localizaiton
sigmaGlobalLocR: 3.0
sigmaGlobalLocT: 0.5
# thresholds and rates to generate accelerations (repulsive and attractive)
repul_thresh: 10.0
repul_rate: 0.05
attr_thresh: 1.0
attr_rate: 0.01
fric_rate: 0.6 # friction
# second destinations
second_dest: true
second_dest_rate: 2.0
# control rate
ctrl_rate: 1.0
# control max
ctrl_max: 1.0
# weights for motion model
alpha1M: 1.0
alpha2M: 0.5
betaM: 0.5

# mode
# 0: no consideration of uncertainty of the other
# 1: consideration of uncertainty of the other
# 2: doubling the unceratinties of both
# 3: biased
# 4: CI
# 5: Centralized
# 6: Particle filter
mode: 3
# mode1 rate
mode1_rateQ: 1.0
# mode2 rate
mode2_rate1: 2.0
mode2_rate2: 2.0
mode2_rateQ: 1.0
# mode3 rate
# if false, it is set to mode3_omega
mode3_omega_variable: false
mode3_omega: 0.95
mode3_rateQ: 1
# mode4 (CI)
# 0: omega = 0.5
# 1: omega = 0 or 1 based on the determinants
# 2: omega = 0.6 or 0.4
# 3: omega = sqrt(det2)/(sqrt(det1) + sqrt(det2))
# others: omega calculated by the formula
mode4_omega_mode: 4
mode4_rateQ: 1.0
# CI with original algorithm if set to true
mode4_original: true
mode4_original_force: false
mode4_original_omega: 0.95
# mode6 (pf) settings
mode6_omega: 0.95
# Number of particles
n_particles: 100
# use random seed for PF
use_random_seed_pf: true
# random seed to give for PF
random_seed_pf: 3000

# enable_update_step
enable_update_step: true
# enable bidirectional mutual update
enable_bidirectional: true
# global localization
enable_global_loc: true
# global localization at every specified steps
global_loc_steps: 1
# network topology
# star, loop, complete, dynamic
topology: complete
# radius of communication area (used when topology is set to dynamic)
comm_radius: 10.0
# robot's locations
robots:
  -
    - 0.0
    - 0.0
  -
    - 1.0
    - 0.0
  -
    - 2.0
    - 0.0
  -
    - 2.0
    - 1.0
  -
    - 2.0
    - 2.0
  -
    - 1.0
    - 2.0
  -
    - 0.0
    - 2.0
  -
    - 0.0
    - 1.0
# random order to update estimates?
enable_random_order: true
# probabilistically update?
enable_prob_update: true
prob_update_p: 1
# every N time steps to plot
plot_interval: 10
