# max time
max_time: 100.0
# simulation update frequendy
sim_freq: 10.0
# weight of motion noise
sigmaM: 1.5
# sigma for floating effect
sigmaF: 0.0
# sigma for sensor model
sigmaS: 0.1
# sigma for global localizaiton
sigmaGlobalLoc: 3.0
# control rate
ctrl_rate: 1.0
# control max
ctrl_max: 1.0
# mode
mode: 0
# enable_update_step
enable_update_step: false
# global localization
enable_global_loc: false
# global localization at every specified steps
global_loc_steps: 1
# network topology
topology: star
# robot's locations
robots:
  -
    - 1.0
    - 2.0
  -
    - 3.0
    - 4.0
  -
    - 5.0
    - 6.0
# random order to update estimates?
enable_random_order: false
# probabilistically update?
enable_prob_update: false
prob_update_p: 1.0
# allow loopy updates (the last robot can communicate with the first one)
enable_loop: false
